application: ffanony
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: django
  version: latest
  
handlers:
- url: /static
  static_dir: staticfiles
- url: /.*
  script: main.app
